import type { RuleDefinition } from "./types";

export const defaultRuleSet: RuleDefinition[] = [
  {
    id: "direct-injection",
    patterns: [
      /ignore\s+(all\s+)?(previous|prior|above)\s+(instructions?|directives?|rules?)/,
      /system\s+override/,
      /developer\s+mode/,
      /jailbreak/,
      /disregard\s+(all\s+)?(prior|previous)\s+instructions?/,
    ],
    risk: "high",
    category: "direct-injection",
    reason: "Instruction override attempt",
  },
  {
    id: "role-escalation",
    patterns: [
      /promote\s+\w+\s+to\s+admin/,
      /grant\s+(me\s+)?admin/,
      /you\s+are\s+now\s+an?\s+admin/,
      /set\s+(my\s+)?role\s+to\s+admin/,
      /make\s+(me|myself|\w+)\s+(an?\s+)?admin/,
      /elevate\s+(my\s+)?privileges?/,
      /migrate\s+\w+\s+to\s+admin/,
      /change\s+(my\s+)?role\s+to\s+(admin|monitor)/,
    ],
    risk: "high",
    category: "role-escalation",
    reason: "Explicit privilege escalation attempt",
  },
  {
    id: "tool-abuse",
    patterns: [
      /execute\s+the\s+(tool|function|command)/,
      /run\s+(the\s+)?(tool|function|command)/,
      /call\s+(the\s+)?(tool|function|command)/,
      /invoke\s+(the\s+)?(tool|function|command)/,
    ],
    risk: "high",
    category: "tool-abuse",
    reason: "Direct tool invocation attempt",
  },
  {
    id: "translation-attack",
    patterns: [
      /translate\s+\S[^.!?]{0,60}(then|and\s+also|after\s+that)\s+(execute|run|apply|do\s+it)/,
      /in\s+(spanish|french|german|chinese|japanese|arabic)\s+\S[^.!?]{0,80}(then|execute|apply)/,
      /say\s+the\s+following\s+in\s+\w+\s+\S[^.!?]{0,80}(and\s+also|then)\s+(promote|update|grant)/,
    ],
    risk: "high",
    category: "translation-attack",
    reason: "Translate-then-execute pattern",
  },
  {
    id: "social-engineering",
    patterns: [
      /my\s+access\s+(level\s+)?(has\s+been|was|is\s+now)\s+upgraded/,
      /i\s+(have\s+been|was)\s+(granted|given)\s+admin/,
      /as\s+a\s+helpful\s+assistant\s+\S[^.!?]{0,150}(reflect|update|change)\s+(my\s+)?role/,
      /you\s+should\s+know\s+that\s+my\s+\S[^.!?]{0,80}(upgraded|elevated|changed)/,
    ],
    risk: "high",
    category: "social-engineering",
    reason: "Social framing to assume unauthorized role change",
  },
  {
    id: "indirect-injection",
    patterns: [
      /for\s+maintenance\s+\S[^.!?]{0,100}(promote|admin)/,
      /apply\s+(any\s+)?(necessary\s+)?(updates|changes)/,
      // Single wildcard group only, avoids multi-group backtracking.
      /summarize\s+\S[^.!?]{0,80}(then\s+)?(apply|execute|run|update|change)/,
      /make\s+sure\s+everything\s+looks\s+correct/,
    ],
    risk: "medium",
    category: "indirect-injection",
    reason: "Possible stored or indirect injection trigger",
  },
  {
    id: "obfuscation",
    patterns: [/\[system\]|\[admin\]|\[override\]|\[instruction\]/, /<system>|<admin>|<override>|<instructions>/],
    risk: "medium",
    category: "obfuscation",
    reason: "XML or markdown tag injection wrapper",
  },
  {
    id: "prompt-leaking",
    patterns: [
      /repeat\s+(your\s+)?(system\s+|initial\s+|original\s+)?instructions?\s+(verbatim|exactly|word\s+for\s+word)/,
      /show\s+me\s+(your\s+)?(system\s+)?prompt/,
      /output\s+(everything|all\s+text)\s+(before|above)\s+(this|the\s+word)/,
      /what\s+(are|were)\s+you\s+(told|instructed|given)/,
      /reveal\s+(your\s+)?(system\s+)?prompt/,
      /print\s+(your\s+)?(initial|system|original)\s+instructions?/,
      /what\s+is\s+(written|said)\s+(above|before)\s+this/,
    ],
    risk: "high",
    category: "prompt-leaking",
    reason: "System prompt extraction attempt",
  },
  {
    id: "jailbreak",
    patterns: [
      /act\s+as\s+DAN/,
      /do\s+anything\s+now/,
      /pretend\s+(you\s+are|to\s+be)\s+an?\s+AI\s+with\s+no/,
      /you\s+are\s+an?\s+AI\s+with\s+no\s+(restrictions?|rules?|limits?|guidelines?)/,
      /imagine\s+you\s+have\s+no\s+(rules?|guidelines?|restrictions?|limits?)/,
      /roleplay\s+as\s+an?\s+(unrestricted|uncensored|unfiltered)/,
      /in\s+(this\s+)?fictional\s+(world|scenario|universe)\s+\S[^.!?]{0,80}(no\s+rules?|no\s+restrictions?|anything\s+goes)/,
      /jailbreak\s+mode/,
      /DAN\s+mode/,
    ],
    risk: "high",
    category: "jailbreak",
    reason: "Persona or roleplay jailbreak attempt",
  },
  {
    id: "data-exfiltration",
    patterns: [
      /summarize\s+all\s+(user|profile|account)/,
      /list\s+\S[^.!?]{0,40}\s+sorted\s+by\s+(trust|privilege|access|role)/,
      /compare\s+all\s+users/,
      /which\s+users?\s+(have|hold|are)\s+(admin|monitor|elevated)/,
      /show\s+me\s+everyone('?s)?\s+(email|role|permission|profile)/,
      /export\s+all\s+(user|profile|account)\s+data/,
    ],
    risk: "medium",
    category: "data-exfiltration",
    reason: "Bulk data access or inference attack",
  },
  {
    id: "excessive-agency",
    patterns: [
      /clean\s+up\s+my\s+account/,
      /make\s+sure\s+my\s+(account|profile)\s+is\s+(in\s+order|set\s+up\s+correctly|optimized)/,
      /do\s+whatever\s+(you\s+think\s+is\s+)?(necessary|needed|best)\s+(for|to)\s+(my\s+)?(account|profile)/,
      /handle\s+everything\s+for\s+my\s+(account|profile)/,
      /take\s+care\s+of\s+(all\s+)?my\s+(account|profile)\s+settings/,
    ],
    risk: "medium",
    category: "excessive-agency",
    reason: "Vague open-ended request that may trigger unintended tool calls",
  },
  {
    id: "stored-injection",
    patterns: [
      // Keyword-pair patterns, no wildcards between keywords, no chained groups.
      /when\s+(it\s+is\s+|this\s+is\s+)?retrieved\s+from\s+(the\s+)?(database|storage|cache|api|system)/,
      /execute\s+(these?\s+)?instructions?\s+when\s+(retrieved|loaded|fetched|read)/,
      /execute\s+(after|upon|following)\s+(retrieval|loading|fetching)/,
      /this\s+document\s+contains\s+instructions?\s+for\s+the\s+assistant/,
      /\[system\s+instructions?\s+embedded\s+in\s+data\]/,
      // Single wildcard group, O(60) max backtracking per position.
      /note\s+to\s+(ai|assistant|llm)\s+\S[^.!?]{0,60}execute/,
      /as\s+a\s+reminder\s+(to\s+)?(the\s+)?(ai|assistant|system)/,
    ],
    risk: "high",
    category: "stored-injection",
    reason: "Instruction embedded in stored or retrieved data",
  },
  {
    id: "role-confusion",
    patterns: [
      /act\s+as\s+a(n?\s+)(helpful|evil|unconstrained|different)\s+\S[^.!?]{0,60}ai/,
      /you\s+are\s+not\s+(an?\s+ai|a\s+language\s+model)/,
      /forget\s+(that\s+)?you\s+are\s+(an?\s+ai|claude|chatgpt|an?\s+assistant)/,
      // Specific keywords, no wildcards needed between "real" and "persona".
      /your\s+(real|true|actual|original)\s+(persona|identity|purpose|role|name)\s+is/,
    ],
    risk: "high",
    category: "role-confusion",
    reason: "Attempt to redefine AI identity or persona",
  },
];
